// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Fs.AL.Typeprovider.Runtime")>]
[<assembly: AssemblyProductAttribute("Fs.AL.Typeprovider")>]
[<assembly: AssemblyDescriptionAttribute("This library is for the .NET platform implementing Fs.AL.Typeprovider.")>]
[<assembly: AssemblyVersionAttribute("1.0.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Fs.AL.Typeprovider.Runtime"
    let [<Literal>] AssemblyProduct = "Fs.AL.Typeprovider"
    let [<Literal>] AssemblyDescription = "This library is for the .NET platform implementing Fs.AL.Typeprovider."
    let [<Literal>] AssemblyVersion = "1.0.0"
    let [<Literal>] AssemblyFileVersion = "1.0.0"
